name: Oran Guncelleme

on:
  workflow_dispatch: # Manuel tetikleme için
  schedule:
    - cron: '0 */3 * * *' # Her 3 saatte bir otomatik çalışması için ekledim

jobs:
  veri-cek:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4
        
      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Kutuphaneleri Yukle
        run: pip install soccerapi
        
      - name: Python Dosyasini Calistir
        run: python scraper.py
        
      - name: Guncel JSON Dosyasini Github'a Yukle
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Kesin Guncelleme"
          file_pattern: "oranlar.json"
